### ISSUE TITLE
Bug: Conflicting peer dependency when upgrading to Vite 5

### ISSUE THREAD

**Issue by hamedbaatour** [xieyhn/vite-plugin-html-resolve-alias#9]
issue encountered while upgrading a Vite 4 project to Vite 5. When running `npm i`, the installation fails due to a conflicting peer dependency on `vite@4.5.3`.

`enforce: "pre"` should be moved outside the `tranfromIndexHtml` hook also using `transfrom` function is deprecated. now you can access the HTML directly from the hook: https://vitejs.dev/guide/api-plugin.html#transformindexhtml

**Comment by xieyhn** [comment]
Hi @hamedbaatour, Thanks for your feedback, vite@5 is now supported in `vite-plugin-html-resolve-alias@2.0.1`!
